let data = [
    {
        id: 'baby',
        title: 'Baby',
        moreToCome: true,
        products: [
            {
                ref: 'BA-2',
                defaultImage: 'BA-2.jpg',
                brand: 'Ikea France',
                name: 'Table a langer',
                details: 'White',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'N/A',
                brandNewPrice: 'N/A',
                price: 'Rs 2,000',
                galleryUrl: 'https://photos.app.goo.gl/H1A4p42JXom5XVdT7',
            },
            {
                ref: 'BA-4',
                defaultImage: 'BA-4.jpg',
                brand: 'Ikea - France',
                name: 'Déco Frames',
                details: 'Format: A4 | Posters included',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'Nov 2018',
                brandNewPrice: '850 Rs',
                price: 'Rs 300',
                galleryUrl: 'https://photos.app.goo.gl/Yb7g729VnXYQz7oU8',
            },
            {
                ref: 'BA-5',
                defaultImage: 'BA-5.jpg',
                brand: 'Lansinoh - amazon.fr',
                name: 'Tire lait electrique',
                details: 'Simple pompage | Sans BPA ni BPS',
                providerUrl:
                    'https://www.lansinoh.fr/products/nouveau-tire-lait-electrique-compact/',
                sold: true,
                batch: 1,
                datePurchased: 'Feb 2019',
                brandNewPrice: '€ 99,99',
                price: 'Rs 3,000',
                galleryUrl: 'https://photos.app.goo.gl/og7qUrNnww2sR7qH9',
            },
            {
                ref: 'BA-6',
                defaultImage: 'BA-6.jpg',
                brand: 'Intermart',
                name: 'Water slide',
                details: '480 cm x 71 cm',
                providerUrl: '',
                sold: false,
                batch: 2,
                datePurchased: 'Dec 2020',
                brandNewPrice: 'Rs 725',
                price: 'Rs 250',
                galleryUrl: 'https://photos.app.goo.gl/dq85dwaFa6TsJMGw7',
            },
            {
                ref: 'BA-7',
                defaultImage: 'BA-7.jpg',
                brand: 'Nuk (france)',
                name: 'Egoutoir à Biberon',
                details: 'Diameter: 30cm | Height: 30cm',
                providerUrl: 'https://www.nuk.fr/nuk-egouttoir-a-biberons.html',
                sold: false,
                batch: 2,
                datePurchased: 'Dec 2018',
                brandNewPrice: 'Rs 900',
                price: 'Rs 350',
                galleryUrl: 'https://photos.app.goo.gl/3kcKF5sgzxQ87DmC7',
            },
            {
                ref: 'BA-8',
                defaultImage: 'BA-8.jpg',
                brand: 'Tati',
                name: 'Pouf / peluche',
                details: 'Diameter: 40cm | Height: 40cm',
                providerUrl: '',
                sold: true,
                batch: 1,
                datePurchased: 'May 2019',
                brandNewPrice: 'N/A',
                price: 'Rs 200',
                galleryUrl: 'https://photos.app.goo.gl/yCj88cRtCHJ8MmKe6',
            },
            {
                ref: 'BA-9',
                defaultImage: 'BA-9.jpg',
                brand: 'N/A',
                name: 'Stool Kid',
                details: 'Height: 22cm',
                providerUrl: '',
                sold: false,
                batch: 2,
                datePurchased: 'May 2020',
                brandNewPrice: 'N/A',
                price: 'Rs 150',
                galleryUrl: 'https://photos.app.goo.gl/gu5AHMp1KfVRhjxP6',
            },
            {
                ref: 'BA-10',
                defaultImage: 'BA-10.jpg',
                brand: 'MyLittleCompany',
                name: 'Veilleuse',
                details: 'Width : 16cm | Bought in France |Battery not incl.',
                providerUrl:
                    'https://www.berceaumagique.com/produit_a-little-lovely-company-veilleuse-nuage-blanc-24-5-cm_171495.html',
                sold: true,
                batch: 2,
                datePurchased: 'May 2020',
                brandNewPrice: 'Rs 850',
                price: 'Rs 200',
                galleryUrl: 'https://photos.app.goo.gl/rwLa6vwdDVpExEmc6',
            },
            {
                ref: 'BA-11',
                defaultImage: 'BA-11.jpg',
                brand: 'E. Leclerc',
                name: 'Coussin de Maternité',
                details: 'Bought in France',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'Dec 2018',
                brandNewPrice: 'Rs 1500',
                price: 'Rs 450',
                galleryUrl: 'https://photos.app.goo.gl/dEWBoCymk2ip1qes6',
            },
            {
                ref: 'BA-12',
                defaultImage: 'BA-12.jpg',
                brand: 'Handmade/ Kinousses',
                name: 'Tour de lit + déco',
                details: 'étagère + pature de lit + déco en bois renard',
                providerUrl: '',
                sold: false,
                batch: 2,
                datePurchased: 'Dec 2018',
                brandNewPrice: 'Rs 2,650',
                price: 'Rs 750',
                galleryUrl: 'https://photos.app.goo.gl/x4po6shKtN34Kyo37',
            },
            {
                ref: 'BA-13',
                defaultImage: 'BA-13.jpg',
                brand: 'Meem',
                name: "Support d'allaitement",
                details: 'Neuf - jamais utilisé | Contre les problèmes de dos',
                providerUrl: '',
                sold: false,
                batch: 2,
                datePurchased: 'October 2018',
                brandNewPrice: 'Rs 1800',
                price: 'Rs 700',
                galleryUrl: 'https://photos.app.goo.gl/39fDRoB191nn5Hp49',
            },
            {
                ref: 'BA-14',
                defaultImage: 'BA-14.jpg',
                brand: 'Atmosphera',
                name: 'Tapis de sol rond',
                details:
                    'Tapis de sol rond, idéal pour Tipi | Diameter: 118 cm',
                providerUrl: '',
                sold: false,
                batch: 2,
                datePurchased: 'Dec 2018',
                brandNewPrice: 'N/A',
                price: 'Rs 350',
                galleryUrl: 'https://photos.app.goo.gl/9CzDouiNupMZiqBr5',
            },
            {
                ref: 'BA-15',
                defaultImage: 'BA-15.jpg',
                brand: 'Bio Oil ',
                name: 'Huile Anti-vergetures',
                details: 'Neuf / 125ml',
                providerUrl: 'https://www.bio-oil.com/fr',
                sold: true,
                batch: 2,
                datePurchased: 'MAI 2021',
                brandNewPrice: 'NA',
                price: 'Rs 200',
                galleryUrl: 'https://photos.app.goo.gl/HsAKcizxyrPek2GNA',
            },
        ],
    },
    {
        id: 'deco',
        title: 'Decoration',
        moreToCome: false,
        products: [
            {
                ref: 'DE-1',
                defaultImage: 'DE-1.jpg',
                brand: 'Mr. Bricolage',
                name: 'Miroir Laiton',
                details: 'Laiton | Diameter 70 cm',
                providerUrl: '',
                sold: true,
                batch: 1,
                datePurchased: 'March 2020',
                brandNewPrice: 'Rs 3,500',
                price: 'Rs 1,500',
                galleryUrl: 'https://photos.app.goo.gl/fNtMh1MehaLhwwPf8',
            },
            {
                ref: 'DE-2',
                defaultImage: 'DE-2.jpg',
                brand: 'Mr. Bricolage',
                name: 'Déco Laiton - 5 items',
                details: 'Laiton | Qty: 5 items | sold in set',
                providerUrl: '',
                sold: true,
                batch: 1,
                datePurchased: 'March 2020',
                brandNewPrice: 'Rs 2,000',
                price: 'Rs 900',
                galleryUrl: 'https://photos.app.goo.gl/bByFaCvfUb2pypbw5',
            },
            {
                ref: 'DE-3',
                defaultImage: 'DE-3.jpg',
                brand: 'Mr. Bricolage',
                name: 'Déco Gris - 5 items',
                details: 'Qty: 5 items | sold in set',
                providerUrl: '',
                sold: true,
                batch: 1,
                datePurchased: 'March 2017',
                brandNewPrice: 'Rs 1,500',
                price: 'Rs 450',
                galleryUrl: 'https://photos.app.goo.gl/TNpgK7CCcWHDVLQU9',
            },
            {
                ref: 'DE-4',
                defaultImage: 'DE-4.jpg',
                brand: 'Hand Made',
                name: 'Abstract paintings x 2',
                details: 'Qty: 2 items | sold in set | 75 x 56cm & 45 x 35cm',
                providerUrl: '',
                sold: false,
                batch: 1,
                datePurchased: 'May 2017',
                brandNewPrice: 'N/A',
                price: 'Rs 1,000',
                galleryUrl: 'https://photos.app.goo.gl/noDJsh3saBgGbtSAA',
            },
            {
                ref: 'DE-5',
                defaultImage: 'DE-5.jpg',
                brand: 'Mr. Bricolage',
                name: 'Grey Curtain x 4',
                details:
                    'Qty: 4 items | sold in set of 2 | 140 x 240 cm | Never used',
                providerUrl: '',
                sold: true,
                batch: 1,
                datePurchased: 'Jan 2021',
                brandNewPrice: 'Rs 350 / unit',
                price: 'Rs 250 / unit',
                galleryUrl: 'https://photos.app.goo.gl/UrdWqz6LgffGCn4SA',
            },
            {
                ref: 'DE-6',
                defaultImage: 'DE-6.jpg',
                brand: 'N/A',
                name: 'Lot vases & arrosoir',
                details: 'Qty: 4 items | sold in set',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'Jan 2019',
                brandNewPrice: 'N/A',
                price: 'Rs 150',
                galleryUrl: 'https://photos.app.goo.gl/hbXnMNq15aRWQavt5',
            },
            {
                ref: 'DE-7',
                defaultImage: 'DE-7.jpg',
                brand: 'NA',
                name: '2 petits tableaux ',
                details: '18 x 13 cm | Qty: 2',
                providerUrl: '',
                sold: false,
                batch: 2,
                datePurchased: '2017',
                brandNewPrice: 'N/A',
                price: 'Rs 250',
                galleryUrl: 'https://photos.app.goo.gl/QA6VaZ2ZyyWvx4Yp6',
            },
            {
                ref: 'DE-8',
                defaultImage: 'DE-8.jpg',
                brand: 'NA',
                name: 'Set de sous plats ',
                details:
                    '8 sous plats plastique + 2 sous plats en bois + 14 sous tasses',
                providerUrl: '',

                sold: true,
                batch: 2,
                datePurchased: '2017',
                brandNewPrice: 'N/A',
                price: 'Rs 400',
                galleryUrl: 'https://photos.app.goo.gl/GucEgckoJrXA2a6YA',
            },
            {
                ref: 'DE-9',
                defaultImage: 'DE-9.jpg',
                brand: 'NA',
                name: 'Luminaire Industriel ',
                details: 'Luminaire Industriel Noir neuf',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'NA',
                brandNewPrice: 'N/A',
                price: 'Rs 375',
                galleryUrl: 'https://photos.app.goo.gl/yj5NfWvxUKcpKAJB7',
            },
        ],
    },
    {
        id: 'electric',
        title: 'Electric Appliances',
        moreToCome: true,
        products: [
            {
                ref: 'EA-1',
                defaultImage: 'EA-1.jpg',
                brand: 'Samsung',
                name: 'Washing Machine',
                details:
                    '8kg | Front loading | Model: EcoBubble - WW80J42 | A+++ | Warranty (Courts) up to Sept 2024',
                providerUrl:
                    'https://www.courtsmammouth.mu/product/samsung-ww80j5260gx-washing-machine.html',
                sold: true,
                batch: 2,
                datePurchased: 'October 2019',
                brandNewPrice: 'Rs 21,789',
                price: 'Rs 11,400',
                galleryUrl: 'https://photos.app.goo.gl/reJRm9vSNAMuSVC59',
            },
            {
                ref: 'EA-2',
                defaultImage: 'EA-2.jpg',
                brand: 'Mr Bricolage',
                name: 'Side lamp',
                details: 'Diameter: 40 cm | Height: 84 cm',
                providerUrl: '',
                sold: true,
                batch: 1,
                datePurchased: 'March 2017',
                brandNewPrice: 'Rs 2,000',
                price: 'Rs 900',
                galleryUrl: 'https://photos.app.goo.gl/3ZBu26ZnrubqCatF6',
            },
            {
                ref: 'EA-3',
                defaultImage: 'EA-3.jpg',
                brand: 'Urban Home',
                name: 'Reading lamp',
                details:
                    'Diameter: 36 cm | Height: 170 cm | Width: 130 cm | Rust dots on the foot',
                providerUrl: '',
                sold: true,
                batch: 1,
                datePurchased: 'March 2017',
                brandNewPrice: 'Rs 5,000',
                price: 'Rs 1,500',
                galleryUrl: 'https://photos.app.goo.gl/R87KgBFX7gYtoHCt5',
            },
            {
                ref: 'EA-4',
                defaultImage: 'EA-4.jpg',
                brand: 'ViewSonic',
                name: 'Computer screen',
                details: 'Quantity: 1 | VX2573-shw | HDMI & VGA connection',
                providerUrl:
                    'https://www.viewsonic.com/eu/products/archive/VX2573-shw',
                sold: true,
                batch: 1,
                datePurchased: 'Dec 2015',
                brandNewPrice: 'Rs 12,190',
                price: 'Rs 2,500',
                galleryUrl: 'https://photos.app.goo.gl/ZEoVf5dzNkbKjjaG8',
            },
            {
                ref: 'EA-5',
                defaultImage: 'EA-5.jpg',
                brand: 'Naturai',
                name: 'Dehumidifier',
                details: '',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'Dec 2013',
                brandNewPrice: 'Rs 4,500',
                price: 'Rs 1000',
                galleryUrl: 'https://photos.app.goo.gl/25KJycCxhKbm9vVg6',
            },
            {
                ref: 'EA-6',
                defaultImage: 'EA-6.jpg',
                brand: 'Rowenta',
                name: 'Vaccum cleaner Xtrem Cleaner + 4 reusable bags',
                details: '',
                providerUrl: 'https://www.rowenta.fr/p/xtrem-power/2211400019',
                sold: true,
                batch: 2,
                datePurchased: 'N/A',
                brandNewPrice: 'N/A',
                price: 'Rs 3,500',
                galleryUrl: 'https://photos.app.goo.gl/iG3F1K2KQU43HV6r8',
            },
            {
                ref: 'EA-7',
                defaultImage: 'EA-7.jpg',
                brand: 'N/A',
                name: 'Toaster',
                details: '',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'N/A',
                brandNewPrice: 'Rs 2 490',
                price: 'Rs 700',
                galleryUrl: 'https://photos.app.goo.gl/WgTQTmeHRyL7bQFY9',
            },
            {
                ref: 'EA-8',
                defaultImage: 'EA-8.jpg',
                brand: 'Moulinex',
                name: 'Rice Cooker',
                details: '',
                providerUrl: 'https://www.moulinex.fr/p/inicio-xl/8000035882',
                sold: true,
                batch: 2,
                datePurchased: 'March 2018',
                brandNewPrice: 'Rs 4 000',
                price: 'Rs 900',
                galleryUrl: 'https://photos.app.goo.gl/V6YMsHNxZq1eKsEU6',
            },
            {
                ref: 'EA-9',
                defaultImage: 'EA-9.jpg',
                brand: 'Panasonic',
                name: 'Blender / Mixer',
                details: '',
                providerUrl:
                    'https://www.panasonic.com/vn/en/consumer/kitchen-appliances/food-processor/bow-mixer/mk-gb1.html',
                sold: true,
                batch: 2,
                datePurchased: 'N/A',
                brandNewPrice: 'N/A',
                price: 'Rs 900',
                galleryUrl: 'https://photos.app.goo.gl/5TkXvoY1ygeSESqDA',
            },
            {
                ref: 'EA-10',
                defaultImage: 'EA-10.jpg',
                brand: 'Apple',
                name: 'Ipad 2',
                details: '',
                providerUrl:
                    'https://www.amazon.com/Apple-Space-Newest-Version-Renewed/dp/B00TREI0D4/ref=sr_1_1?dchild=1&keywords=ipad+2&qid=1626426428&sr=8-1',
                sold: true,
                batch: 2,
                datePurchased: 'Dec 2017',
                brandNewPrice: 'Rs 9,000',
                price: 'Rs 1,500',
                galleryUrl: 'https://photos.app.goo.gl/u9phWJ8o1nPcR7Zb6',
            },
            {
                ref: 'EA-11',
                defaultImage: 'EA-11.jpg',
                brand: 'Babyliss',
                name: 'Lisseur',
                details: '2 ans de garantie',
                providerUrl:
                    'https://www.galaxy.mu/product/beauty-body-care/hair-dryers-stylers/hair-straighteners/babyliss-hair-straightener-st387e-grey/',
                sold: false,
                batch: 2,
                datePurchased: 'Novembre 2021',
                brandNewPrice: 'Rs 3,790',
                price: 'Rs 1,700',
                galleryUrl: 'https://photos.app.goo.gl/VFNmYnc4SsKLzSdSA',
            },
            {
                ref: 'EA-12',
                defaultImage: 'EA-12.jpg',
                brand: 'Saeco',
                name: 'Coffee Machine',
                details: 'Manual: https://bit.ly/3rhai1a',
                providerUrl:
                    'https://mauritius.desertcart.com/products/48435792-saeco-10004476-espresso-coffee-machine-for-coffee-lovers-or-just-for-the-office',
                sold: false,
                batch: 2,
                datePurchased: 'Novembre 2017',
                brandNewPrice: 'Rs 40,669',
                price: 'Rs 9,800',
                galleryUrl: 'https://photos.app.goo.gl/n6rAz9Kf79P9u8xw8',
            },
        ],
    },
    {
        id: 'furnitures',
        title: 'Furnitures',
        moreToCome: true,
        products: [
            {
                ref: 'FU-1',
                defaultImage: 'FU-1.jpg',
                brand: 'Teak World',
                name: 'TV cabinet - 2 slots',
                details:
                    'Teak | 2 drawers | Largeur: 120cm | Hauteur: 50 cm | Profondeur: 45 cm',
                providerUrl: '',
                sold: true,
                batch: 1,
                datePurchased: 'March 2020',
                brandNewPrice: 'Rs 16,000',
                price: 'Rs 8,000',
                galleryUrl: 'https://photos.app.goo.gl/NCgEQvduvjQ9skbL8',
            },
            {
                ref: 'FU-14',
                defaultImage: 'FU-14.jpg',
                brand: 'Teak World',
                name: 'TV cabinet - 3 slots',
                details:
                    'Teak | 3 drawers | Largeur: 180cm | Hauteur: 50 cm | Profondeur: 45 cm',
                providerUrl: '',
                sold: true,
                batch: 1,
                datePurchased: 'March 2020',
                brandNewPrice: 'Rs 26,900',
                price: 'Rs 13,000',
                galleryUrl: 'https://photos.app.goo.gl/8J6QGVh41WyG1zYT9',
            },
            {
                ref: 'FU-2',
                defaultImage: 'FU-2.jpg',
                brand: 'Teak World',
                name: 'Teak Console',
                details:
                    'Teak | 2 drawers | Longueur: 140 cm | Largeur: 40 cm | Hauteur: 80 cm',
                providerUrl: '',
                sold: true,
                batch: 1,
                datePurchased: 'March 2020',
                brandNewPrice: 'Rs 25,900',
                price: 'Rs 13,000',
                galleryUrl: 'https://photos.app.goo.gl/b1AB9RNaaqVxKGQcA',
            },
            {
                ref: 'FU-3',
                defaultImage: 'FU-3.jpg',
                brand: 'Teak World',
                name: 'Dinning table + 8 chairs',
                details:
                    'Teak | 8 Seaters | Longueur: 200 cm | Largeur: 100 cm | Hauteur: 75 cm',
                providerUrl: '',
                sold: true,
                batch: 1,
                datePurchased: 'March 2017',
                brandNewPrice: 'Rs 81,820',
                price: 'Rs 45,000',
                galleryUrl: 'https://photos.app.goo.gl/ThZLT7ovXdKih5639',
            },
            {
                ref: 'FU-4',
                defaultImage: 'FU-4.jpg',
                brand: 'Teak World',
                name: 'Pouffe tabouret',
                details: 'Diameter: 50 cm  | Height: 43 cm',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'March 2020',
                brandNewPrice: 'Rs 8,000',
                price: 'Rs 3,600',
                galleryUrl: 'https://photos.app.goo.gl/3qMPysUESCvW9K9M8',
            },
            {
                ref: 'FU-5',
                defaultImage: 'FU-5.jpg',
                brand: 'Urban Home',
                name: 'Nordic Lounge Chair',
                details: 'Length: 57 cm | Width: 69cm | Height: 75 cm',
                providerUrl: '',
                sold: true,
                batch: 1,
                datePurchased: 'March 2020',
                brandNewPrice: 'Rs 8,625',
                price: 'Rs 4,000',
                galleryUrl: 'https://photos.app.goo.gl/tAYFwhxDzKFeZZ949',
            },
            {
                ref: 'FU-6',
                defaultImage: 'FU-6.jpg',
                brand: 'Urban Home',
                name: 'Nordic 3 Seater sofa',
                details:
                    'Length: 215 cm | Width: 91 cm | height: 72 cm | 4 cousins gris déhoussable ',
                providerUrl:
                    'https://www.urbanhome.mu/collections/sofas/products/geneva',
                sold: true,
                batch: 1,
                datePurchased: 'March 2020',
                brandNewPrice: 'Rs 26,900',
                price: 'Rs 13 000',
                galleryUrl: 'https://photos.app.goo.gl/kP4MVYwcmGUGX8kaA',
            },
            {
                ref: 'FU-7',
                defaultImage: 'FU-7.jpg',
                brand: 'Tati',
                name: 'Side table set',
                details: 'Each table has a different height | sold in set',
                providerUrl: '',
                sold: true,
                batch: 1,
                datePurchased: 'May 2017',
                brandNewPrice: 'Rs 2 000',
                price: 'Rs 400',
                galleryUrl: 'https://photos.app.goo.gl/FNPzWCcSWY6ZYp7P7',
            },
            {
                ref: 'FU-8',
                defaultImage: 'FU-8.jpg',
                brand: 'Made by Carpenter',
                name: 'Office desk x 2',
                details:
                    'Quantity: 2 | Width: 94 cm | Length: 175 cm | Height: 75 cm | Black MDF with merenti frame Around the top',
                providerUrl: '',
                sold: false,
                batch: 2,
                datePurchased: 'May 2017',
                brandNewPrice: 'Rs 16 000 / unit',
                price: 'Rs 3 000 Rs / unit',
                galleryUrl: 'https://photos.app.goo.gl/nMs7XJJfhYUFQzNT9',
            },
            {
                ref: 'FU-9',
                defaultImage: 'FU-9.jpg',
                brand: 'Urban Home',
                name: 'White chair',
                details: 'Height: 80 cm | Depth: 62 cm | Width: 60cm | Plastic',
                providerUrl: '',
                sold: true,
                batch: 1,
                datePurchased: 'May 2019',
                brandNewPrice: 'Rs 2,000',
                price: 'Rs 750',
                galleryUrl: 'https://photos.app.goo.gl/9jTmJMPohib5fb9Z9',
            },
            {
                ref: 'FU-10',
                defaultImage: 'FU-10.jpg',
                brand: 'Tailor made',
                name: 'Shoe rack',
                details:
                    'Merenti "ajouté" | Depth: 33cm | Height: 75 cm | Width: 100 cm | Fits 18 pairs of shoes easily',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'June 2017',
                brandNewPrice: 'Rs 11,000',
                price: 'Rs 4,500',
                galleryUrl: 'https://photos.app.goo.gl/dEgDuEbjezZRou2UA',
            },
            {
                ref: 'FU-11',
                defaultImage: 'FU-11.jpg',
                brand: 'Tailor made',
                name: 'Single bed x 2',
                details: 'Merenti "ajouté" | Qty: 2 | 190 x 90',
                providerUrl: '',
                sold: true,
                batch: 1,
                datePurchased: 'April 2017',
                brandNewPrice: 'Rs 13,000 / unit',
                price: 'Rs 3,500 / unit',
                galleryUrl: 'https://photos.app.goo.gl/PAMkuT6pFVyGmNY26',
            },
            {
                ref: 'FU-12',
                defaultImage: 'FU-12.jpg',
                brand: 'Dream On Matress (Kalachand)',
                name: 'White Orthopaedic Matress x 2',
                details: 'Qty: 2 | 190 x 90',
                providerUrl: '',
                sold: true,
                batch: 1,
                datePurchased: 'April 2017',
                brandNewPrice: 'Rs 6,650 / unit',
                price: 'Rs 2,500 / unit',
                galleryUrl: 'https://photos.app.goo.gl/QC2yeQRDo2SQpMrx7',
            },
            {
                ref: 'FU-13',
                defaultImage: 'FU-13.jpg',
                brand: 'Dream On Matress (Kalachand)',
                name: 'Grey Orthopaedic Matress',
                details: 'Qty: 1 | 190 x 90',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'Mai 2018',
                brandNewPrice: 'Rs 5,932',
                price: 'Rs 2,000',
                galleryUrl: 'https://photos.app.goo.gl/squtqGkKKcRy2PRYA',
            },
            {
                ref: 'FU-15',
                defaultImage: 'FU-15.jpg',
                brand: 'Teak World',
                name: 'Teak Coffee Table',
                details: 'Width: 80cm | Length: 80 cm | Height: 45 cm',
                providerUrl: '',
                sold: true,
                batch: 1,
                datePurchased: 'Mai 2017',
                brandNewPrice: 'Rs 15,900',
                price: 'Rs 7,800',
                galleryUrl: 'https://photos.app.goo.gl/rMyxm3GAbHSCLXND9',
            },
            {
                ref: 'FU-16',
                defaultImage: 'FU-16.jpg',
                brand: 'Mr.Bricolage',
                name: 'Etagère',
                details:
                    'Width: 70cm | Length: 70 cm | Height: 170 cm | Pine wood | Color: Grey',
                providerUrl: '',
                sold: false,
                batch: 2,
                datePurchased: 'Nov 2019',
                brandNewPrice: 'Rs 3,000',
                price: 'Rs 700',
                galleryUrl: 'https://photos.app.goo.gl/aSNG7MeyQBtnNYq58',
            },
        ],
    },
    {
        id: 'kitchen',
        title: 'Kitchen',
        moreToCome: true,
        products: [
            {
                ref: 'KI-1',
                defaultImage: 'KI-1.jpg',
                brand: 'Beko',
                name: 'Micro Waves',
                details: 'Width: 45cm | Depth: 35cm | Height: 26cm',
                providerUrl: '',
                sold: true,
                batch: 1,
                datePurchased: 'March 2017',
                brandNewPrice: 'Rs 3,500',
                price: 'Rs 700',
                galleryUrl: 'https://photos.app.goo.gl/7VkiVRK5BTsvcspTA',
            },
            {
                ref: 'KI-2',
                defaultImage: 'KI-2.jpg',
                brand: 'N/A',
                name: 'Small Tupperwares x 4',
                details: 'Length between 13 to 17 cm',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'March 2018',
                brandNewPrice: 'N/A',
                price: 'Rs 100',
                galleryUrl: 'https://photos.app.goo.gl/vqefpkjKRf9TpbHP6',
            },
            {
                ref: 'KI-3',
                defaultImage: 'KI-3.jpg',
                brand: 'Super U',
                name: 'Essoreuse',
                details: 'Diameter: 26cm | Height: 16 cm',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'March 2021',
                brandNewPrice: 'Rs 620',
                price: 'Rs 350',
                galleryUrl: 'https://photos.app.goo.gl/CjEif3xApCbUHEpi6',
            },
            {
                ref: 'KI-4',
                defaultImage: 'KI-4.jpg',
                brand: 'N/A',
                name: 'Pastry Set',
                details:
                    'Paper cake cups | Measuring spoons: 60ml, 120ml & 240 ml | Moule oeuf de paques',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'March 2020',
                brandNewPrice: 'N/A',
                price: 'Rs 200',
                galleryUrl: 'https://photos.app.goo.gl/12Dzyi576yhrdrXJ6',
            },
            {
                ref: 'KI-5',
                defaultImage: 'KI-5.jpg',
                brand: 'N/A',
                name: 'Rouleau a patisserie',
                details: 'Length : 37 cm | Wood',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'March 2020',
                brandNewPrice: 'Rs 300',
                price: 'Rs 150',
                galleryUrl: 'https://photos.app.goo.gl/MNUx6gogeNQ2fvez8',
            },
            {
                ref: 'KI-7',
                defaultImage: 'KI-7.jpg',
                brand: 'Tefal',
                name: 'Balance Tefal',
                details: '',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'Jan 2021',
                brandNewPrice: 'Rs 1,800',
                price: 'Rs 900',
                galleryUrl: 'https://photos.app.goo.gl/GXA6aFmy9CKCtvb96',
            },
            {
                ref: 'KI-8',
                defaultImage: 'KI-8.jpg',
                brand: 'Super U',
                name: 'Saladier',
                details: '',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'Jan 2021',
                brandNewPrice: 'Rs 620',
                price: 'Rs 100',
                galleryUrl: 'https://photos.app.goo.gl/6LB9EEUZQDiNrSck8',
            },
            {
                ref: 'KI-9',
                defaultImage: 'KI-9.jpg',
                brand: 'N/A',
                name: 'Cooking balance',
                details: '',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'Jan 2021',
                brandNewPrice: 'Rs 620',
                price: 'Rs 150',
                galleryUrl: 'https://photos.app.goo.gl/qKJM4jX19vBWj9Rd8',
            },
            {
                ref: 'KI-10',
                defaultImage: 'KI-10.jpg',
                brand: 'Tescoma/pedrini/super U',
                name: 'Cuillères/spatules/presse purée + pot à ustensiles',
                details: 'Presse purée quasi neuf',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'NA',
                brandNewPrice: 'Rs 1150',
                price: 'Rs 450',
                galleryUrl: 'https://photos.app.goo.gl/KvbxCCW8ELtQYf6cA',
            },
            {
                ref: 'KI-11',
                defaultImage: 'KI-11.jpg',
                brand: 'Super U',
                name: 'Verre x 6',
                details: 'Verres x 6',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'Mai 2021',
                brandNewPrice: 'Rs 350',
                price: 'Rs 175',
                galleryUrl: 'https://photos.app.goo.gl/wbMKM2B3tbyALU1i7',
            },
            {
                ref: 'KI-12',
                defaultImage: 'KI-12.jpg',
                brand: 'NA',
                name: 'Lot Couverts',
                details:
                    'Cuillère x 12, Fourchette x 13, Couteaux x13, \nPetites cuillère x 5,\npetite fourchette x 2, ouvre boîte, \nbouchon conservation, range couverts',
                providerUrl: '',

                sold: true,
                batch: 2,
                datePurchased: 'Mai 2017',
                brandNewPrice: 'Rs 4000',
                price: 'Rs 1500',
                galleryUrl: 'https://photos.app.goo.gl/BxkL5eJYHJoWhAMq7',
            },
            {
                ref: 'KI-13',
                defaultImage: 'KI-13.jpg',
                brand: 'Joseph Joseph',
                name: 'Bac rangement évier',
                details: '',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'December 2020',
                brandNewPrice: 'Rs 490',
                price: 'Rs 250',
                galleryUrl: 'https://photos.app.goo.gl/GovexBwdwkSX4vWz8',
            },
            {
                ref: 'KI-14',
                defaultImage: 'KI-14.jpg',
                brand: 'Pyrex',
                name: 'Doseur',
                details: '0.5L Doseur Pyrex',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'Février 2021',
                brandNewPrice: 'N/A',
                price: 'Rs 175',
                galleryUrl: 'https://photos.app.goo.gl/DPnsh7BmLxgmXz1h9',
            },
            {
                ref: 'KI-15',
                defaultImage: 'KI-15.jpg',
                brand: 'Joseph Joseph',
                name: 'Presse Agrume',
                details: 'Presse Agrume Joseph Joseph',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'Février 2022',
                brandNewPrice: 'Rs 320',
                price: 'Rs 150',
                galleryUrl: 'https://photos.app.goo.gl/LDm2zzywnFcStobX7',
            },
            {
                ref: 'KI-16',
                defaultImage: 'KI-16.jpg',
                brand: 'NA',
                name: 'Lot de couteaux ',
                details:
                    "Lot de 4 couteaux dont 1 neuf et l'autre acheté il y a un mois",
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'NA',
                brandNewPrice: 'Rs 900',
                price: 'Rs 200',
                galleryUrl: 'https://photos.app.goo.gl/oKXP1xpZvzscTqhY6',
            },
            {
                ref: 'KI-17',
                defaultImage: 'KI-17.jpg',
                brand: 'Tescoma/Super U',
                name: "Lot d'ustensiles de cuisine",
                details: 'économe, maryse, cuillère à glace, passoire',
                sold: true,
                providerUrl: '',
                batch: 2,
                datePurchased: 'NA',
                brandNewPrice: 'Rs 700',
                price: 'Rs 325',
                galleryUrl: 'https://photos.app.goo.gl/KW3U5coZX8Ww3ndBA',
            },
            {
                ref: 'KI-18',
                defaultImage: 'KI-18.jpg',
                brand: 'NA',
                name: 'Set de paniers',
                details: 'panier de fruits + paniers à pain',
                providerUrl: '',

                sold: true,
                batch: 2,
                datePurchased: '2017',
                brandNewPrice: 'N/A',
                price: 'Rs 200',
                galleryUrl: 'https://photos.app.goo.gl/8Pm9uJUrjNN7zsceA',
            },
            {
                ref: 'KI-19',
                defaultImage: 'KI-19.jpg',
                brand: 'NA',
                name: 'lot : passoire, chinois & rape',
                details: 'lot : passoire, chinois & rape',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: '2017',
                brandNewPrice: 'Rs 750',
                price: 'Rs 275',
                galleryUrl: 'https://photos.app.goo.gl/H4XBm3q7TApw78GE8',
            },
            {
                ref: 'KI-20',
                defaultImage: 'KI-20.jpg',
                brand: 'NA',
                name: 'Casseroles',
                details: 'Lot de 5 casseroles',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'NA',
                brandNewPrice: 'N/A',
                price: 'Rs 600',
                galleryUrl: 'https://photos.app.goo.gl/PxmaBMfeZ2uvbBra6',
            },

            {
                ref: 'KI-21',
                defaultImage: 'KI-21.jpg',
                brand: 'NA',
                name: 'Lot de plats et sauciers',
                details:
                    'Plats Oven Safe x 3 + sauciers x 4 + bols de céréales x 2',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'Mai 2017',
                brandNewPrice: 'Rs 900',
                price: 'Rs 400',
                galleryUrl: 'https://photos.app.goo.gl/ggvFqXtXw8MfdNMeA',
            },
            {
                ref: 'KI-22',
                defaultImage: 'KI-22.jpg',
                brand: 'Excelent Houseware',
                name: 'Torchon Four',
                details: 'Set Torchons four quasi neuf x 2',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'Juin 2021',
                brandNewPrice: 'Rs 300',
                price: 'Rs 150',
                galleryUrl: 'https://photos.app.goo.gl/Xft3FBkpxzUJ6tYJ6',
            },
            {
                ref: 'KI-23',
                defaultImage: 'KI-23.jpg',
                brand: 'NA',
                name: 'Panier à linge',
                details: 'Panier à linges',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'Mai 2017',
                brandNewPrice: 'Rs 900',
                price: 'Rs 250',
                galleryUrl: 'https://photos.app.goo.gl/5S2Q2rzrW3tYGo3H7',
            },
            {
                ref: 'KI-24',
                defaultImage: 'KI-24.jpg',
                brand: 'Sunnex',
                name: 'Thermos',
                details: '1L ',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'Mai 2017',
                brandNewPrice: 'Rs 900',
                price: 'Rs 400',
                galleryUrl: 'https://photos.app.goo.gl/EPFD4VT3MCJa8VKL6',
            },
            {
                ref: 'DI-2',
                defaultImage: 'DI-2.jpg',
                brand: 'N/A',
                name: 'Verres à verrine x 10',
                details: 'Diameter: 5.5cm | Height: 10cm',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'March 2020',
                brandNewPrice: 'N/A',
                price: 'Rs 200',
                galleryUrl: 'https://photos.app.goo.gl/zs25YQ8eichuDip47',
            },
            {
                ref: 'DI-4',
                defaultImage: 'DI-4.jpg',
                brand: 'N/A',
                name: 'Set assiètes: 8 Grandes + 13 petites',
                details: 'Color: white | Diametre: 20cm > 28cm',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'March 2018',
                brandNewPrice: 'N/A',
                price: 'Rs 350',
                galleryUrl: 'https://photos.app.goo.gl/Bfqg3fZJkbSKQHcr7',
            },
            {
                ref: 'DI-11',
                defaultImage: 'DI-11.jpg',
                brand: 'N/A',
                name: "Carafe d'eau x 2",
                details: 'Volume: 0.5 L & 2 L',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'March 2019',
                brandNewPrice: 'N/A',
                price: 'Rs 125',
                galleryUrl: 'https://photos.app.goo.gl/q4cDsfRVxehzS46G6',
            },
        ],
    },
    {
        id: 'textile',
        title: 'Textile',
        moreToCome: false,
        products: [
            {
                ref: 'TE-1',
                defaultImage: 'TE-1.jpg',
                brand: 'Associated Textiles',
                name: 'Protège matelas',
                details: '140 x 90 | Never used',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'March 2021',
                brandNewPrice: 'Rs 800',
                price: 'Rs 400',
                galleryUrl: 'https://photos.app.goo.gl/rPHQ8LsctZtjtrmCA',
            },
            {
                ref: 'TE-2',
                defaultImage: 'TE-2.jpg',
                brand: 'Sofimex',
                name: 'Duvet/Couette',
                details: 'Single bed',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'March 2019',
                brandNewPrice: 'N/A',
                price: 'Rs 200',
                galleryUrl: 'https://photos.app.goo.gl/ibfp1iHGia7JoAQB6',
            },
            {
                ref: 'TE-3',
                defaultImage: 'TE-3.jpg',
                brand: 'Espace Maison',
                name: 'Lot 3 coussins gris',
                details: 'Bon état',
                providerUrl: '',
                sold: true,
                batch: 2,
                datePurchased: 'Janvier 2021',
                brandNewPrice: 'Rs 1800',
                price: 'Rs 500',
                galleryUrl: 'https://photos.app.goo.gl/KPZpzV622t9eaohX9',
            },
            {
                ref: 'TE-4',
                defaultImage: 'TE-4.jpg',
                brand: 'Monoprix & Tati',
                name: 'Lot House de couette x 2',
                details: 'Dimension : 180 x 200',
                sold: true,
                providerUrl: '',
                batch: 2,
                datePurchased: 'Août 2017',
                brandNewPrice: 'Rs 2100',
                price: 'Rs 400',
                galleryUrl: 'https://photos.app.goo.gl/tY5Ae8RZAMbfqMgu8',
            },
        ],
    },
    // {
    //     id: 'others',
    //     title: 'Others',
    //     moreToCome: false,
    //     products: [
    //         {
    //             ref: 'OT-1',
    //             defaultImage: 'OT-1.jpg',
    //             brand: 'N/A',
    //             name: 'Toothbrush holder',
    //             details: '',
    //             providerUrl: '',
    //             sold: true,
    //             batch: 2,
    //             datePurchased: 'March 2021',
    //             brandNewPrice: 'N/A',
    //             price: 'Rs 100',
    //             galleryUrl: 'https://photos.app.goo.gl/hDxfL9QitDitF2rcA',
    //         },
    //     ],
    // },
]
